name: Common Setup
description: |
  This action sets up a common environment for Python development,
  including installing Python, creating a virtual environment, and caching dependencies.

inputs:
  python_version:
    description: The version of Python to install (e.g., '3.10', '3.11').
    required: false
    default: "3.11"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.14"
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"

    - name: Install Python
      shell: bash
      run: uv python install --version "${{ inputs.python_version }}"

    - name: Create Virtual Environment
      shell: bash
      run: uv venv

    - name: Cache Virtual Environment
      id: venv-cache
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Install Python Dependencies
      if: steps.venv-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "::group::Install Python Dependencies"
        uv sync
        echo "::endgroup::"
