repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  # Lint and format python source files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml
          - --fix
      - id: ruff-format
        args:
          - --config=pyproject.toml
          - --fix

  # Lint github actions workflow files
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.6
    hooks:
      - id: actionlint

  # Use local mypy script to check types, using the uv venv, which pre-commit/mirrors-mypy cannot do
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: script
        entry: bin/run-mypy
        pass_filenames: false
  